// This file is generated by Firebase Genkit.
// Manual changes might be lost - proceed with caution!

'use server';

/**
 * @fileOverview Provides an initial prompt or suggested prompts to new users to showcase the Venice AI model's capabilities.
 *
 * @exports initialPromptFlow - The Genkit flow for generating initial prompts.
 * @exports getInitialPrompt - A function to invoke the initialPromptFlow.
 * @exports InitialPromptInput - The input type for the flow (currently empty).
 * @exports InitialPromptOutput - The output type for the flow, containing the initial prompt.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema (currently empty)
const InitialPromptInputSchema = z.object({});
export type InitialPromptInput = z.infer<typeof InitialPromptInputSchema>;

// Define the output schema
const InitialPromptOutputSchema = z.object({
  initialPrompt: z.string().describe('A suggested initial prompt for the user.'),
});
export type InitialPromptOutput = z.infer<typeof InitialPromptOutputSchema>;

// Define the flow
const initialPromptFlow = ai.defineFlow(
  {
    name: 'initialPromptFlow',
    inputSchema: InitialPromptInputSchema,
    outputSchema: InitialPromptOutputSchema,
  },
  async () => {
    const {output} = await initialPrompt({
      // No input needed for now
    });
    return output!;
  }
);

// Define the prompt
const initialPrompt = ai.definePrompt({
  name: 'initialPrompt',
  prompt: `You are Venice AI. Provide a few example prompts to showcase your capabilities to a new user. 

  Example Prompts:
  1. "Explain the key differences between Javascript and Typescript"
  2. "Summarize the plot of the Lord of the Rings"
  3. "Write a poem about the ocean"
  
  Return the prompts in a welcome message. Be personable and helpful.
  Start with "Welcome to Venice AI! Here are some prompts to get you started:"
  `,
  output: {schema: InitialPromptOutputSchema},
  config: {
    model: 'googleai/gemini-pro',
  },
});

/**
 * Retrieves an initial prompt for the Venice AI model.
 * @returns A promise that resolves to an InitialPromptOutput object.
 */
export async function getInitialPrompt(): Promise<InitialPromptOutput> {
  return initialPromptFlow({});
}
